services:
  # Backend API
  - type: web
    name: passos-magicos-api
    runtime: docker
    env: python
    region: ohio
    plan: free
    rootDir: backend
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  # Frontend Dashboard
  - type: static_site
    name: passos-magicos-dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: dist


    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: passos-magicos-api
          property: host
